### ISSUE TITLE
S34 Create/Associate team during project creation

### ISSUE THREAD

**Issue by hecerinc** [ProyectoIntegrador2018/BlueMarket#102]
# S34

**Priority** 2

As a user, I can associate an existing team of which I am part of or create a new team during the project creation workflow.

## Conversation

- [x] When **associating**, the system should validate the users that already belong that team are associated to the course as well, else block the association.
- [x] When creating the team, the user will provide all of the information without losing context of the project creation workflow.

## To-Dos

- [x] Validate with users

## Acceptance criteria

- [x] The user successfully creates or associates a team **and** a project in a single-context view
- [x] Teams with members outside of the course should not be valid for association
- [x] The project and team should be associated when the project creation workflow is finished.

**Comment by katiearriagam** [comment]
Reopening porque hay un to-do pendiente. Si ya está listo para cerrarse entonces please hay que:

- marcar todos los to-dos (si ya están)
- agregar label de :done:
- volver a mover a la columna de done en el project (la regresé a in progress por ahora)
- close issue! ⭐️
