### ISSUE TITLE
Remove team max. size from front-end and back-end

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#107]
This constraint is no longer needed and should be removed. 

# Conversation
Professors do not need to add this contraint to their groups.

# To-do
- [x] Update front-end course registration and details 
- [x] Update back-end course registration and details 

# Related 
- [S03](https://github.com/ProyectoIntegrador2018/BlueMarket/issues/36)
- [S32](https://github.com/ProyectoIntegrador2018/BlueMarket/issues/82)

# Acceptance criteria
- [x] A course can be successfully registered on the platform (max team size is not asked for)
- [x] Course details are shown after course registration and do not show the team size (no longer exists)
- [x] Course details are shown after selecting a project from projects lists and do not show the team size (no longer exists)
