### ISSUE TITLE
Redirect to project details view after project creation

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#108]
Redirect to project details view after project creation

# Conversation
To show a successfully created project, we should redirect to the project details view. 

# To-do
- [x] Photo download logic added here so that project photo is shown. 
- [x] Update project controller to redirect to project details after project creation.

# Related 
- [S02](https://github.com/ProyectoIntegrador2018/BlueMarket/issues/26)
- [S12](https://github.com/ProyectoIntegrador2018/BlueMarket/issues/6)

- [#34](https://github.com/ProyectoIntegrador2018/BlueMarket/issues/34)

# Acceptance criteria
- [x] After a project is created successfully, the user is redirected to the project details view of the project that was just created.
