### ISSUE TITLE
S35 Teacher login

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#114]
# S35

Priority 1

As `teacher`, I can `login to the system` to `gain access to the views relevant to teachers`.

## Conversation

- We should use Google auth. 
- System admins register professors in the system.

## To-do

- [ ] Login view for professors (check if this is needed or if we are reusing login view - probably the latter). 
- [ ] Authenticate professors.

## Acceptance criteria

- [ ] A teacher that is registered in the system gains access to teacher views.
- [ ] A teacher that is not registered in the system is not able to log in.
