### ISSUE TITLE
S36 System admin login

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#115]
# S36

Priority 1

As `system admin`, I can `login to the system` to `gain access to the views relevant to system admins`.

## Conversation

- We should use Google auth. 
- System admins are pre-registered in the system.

## To-do

- [ ] Login view for system admin (check if this is needed or if we are reusing login view - probably the latter). 
- [ ] Authenticate system admins.

## Acceptance criteria

- [ ] A system admin that is registered in the system gains access to the system admin views.
- [ ] A system admin that is not registered in the system is not able to log in.
