### ISSUE TITLE
Student navigation (includes menu)

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#116]
Create the dropdown menu for students which is used to navigate across the application. 

## Conversation

Must include the views relevant to students which are not part of the menu (e.g. my profile, new project, new team). 

## To-do

- [x] Define list of views that the student should navigate to. 
- [x] Choose how the student will navigate to each view. 
- [x] Add the navigation that will be used to access such routes.
- [x] Test that all routes are accessible to the student. 

## Acceptance criteria

- [x] The student can navigate to all the routes relevant to their role.
