### ISSUE TITLE
Teacher navigation (includes menu)

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#117]
Create the dropdown menu for teachers which is used to navigate across the application. 

## Conversation

Must provide a way to access the views relevant to teachers (e.g. New course, My courses). 

## To-do

- [x] Define list of views that the teacher should navigate to. 
- [x] Define navigation to the views. 
- [x] Add the menu/dropdown menu and corresponding routes.
- [x] Test navigation through the menu. 

## Acceptance criteria

- [x] The teacher can navigate to all the views relevant to their role.
