### ISSUE TITLE
S37 Student search for students

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#118]
# S37

Priority 3

As a `student`, I can `search for other students in the system` to `learn more about their portfolio`.

## Conversation
- Search should include pagination
- TBD: define search filters (name? skills?)
- Clicking on the student card should redirect to the student profile view

## To-do
- [x] Search view (includes student cards) #166 
- [x] Student card #122 
- [x] Student profile view #121 
- [x] Pagination (back-end) Created a new issue for it.
- [x] Search functionality
- [x] FE and BE integration 

## Acceptance criteria

- [x] When filtering students, the system should show only the cards of the students that match the filter.
- [x] When a student clicks on a student card, they are redirected to that student's profile.
