### ISSUE TITLE
S27 As a student, I can register as a user on the platform via social media

### ISSUE THREAD

**Issue by hecerinc** [ProyectoIntegrador2018/BlueMarket#12]
# S27 Register as user
Priority 1
As a student, I can register as a user on the platform to be able to interact with the platform.
## Conversation
- Users will their e-mail as a unique identifier
## To-do
- [x] First POC: via Gmail (Proof of Concept)
- [ ] [enhancement] Consider adding Facebook integration
- [x] Ask user to fill their profile ("Complete your profile so that users can get to know your skills")
    - Solo el link (redirect)
- [x] Create register form
- [x] Update navbar 
- [x] Integration FE and BE

## Acceptance criteria
- [x] When a student registers as a new user, her entry should be added in the DB.

### Related

- #4 
- #3 

## Wireframes
![image](https://user-images.githubusercontent.com/14140121/53188443-fa44f580-35ca-11e9-86c4-ed6a2ebcb79a.png)

**Comment by hecerinc** [comment]
Fixed by #66
