### ISSUE TITLE
Create student profile view

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#121]
This is the view that presents all the information relevant to each `student`.

## Conversation
- TBD: do we need to 'contact' (mailto) student for all except self?
- The user profile view should include: user basic info (name, skills, avatar), the user's projects, the user's teams, and user's courses.
- The view should only load for auth'd users.
- The route should be something like `users/{id}/` because every auth'd user should be able to see the profile for other students.
- Profiles should not be accessible if the user is not auth'd.

## To-do
- [x] Profile view presents all relevant user info. (front-end)
- [x] Send user info to front-end. This includes: user basic info (name, skills, avatar), the user's projects (everything needed to create project card), the user's teams (team photo, team name, team id) and user's courses (name, professor, schedule).  (back-end)
- [x] For the auth'd user, if they are looking at their own profile, an `edit` button should be presented which redirects to the edit view ([S04](https://github.com/ProyectoIntegrador2018/BlueMarket/issues/29)). (front-end & back-end)
- [x] Check if user is auth'd. If not, redirect to login. (back-end)
- [x] For the auth'd user, if they are looking at their own profile, they should be able to add a new course from this view. **Note: Student-course association is already implemented. See: [S11](https://github.com/ProyectoIntegrador2018/BlueMarket/issues/33)**. (front-end & back-end)
- [x] Generating obsufscated mailto tag

## Comments
- Href in Edit button should redirect to Edit Profile view
- Need to show gray image when user doesn't have an image registered yet
- Wireframes (3; one for each tab)

## Acceptance criteria
- [x] When going to a student profile url, if the user is auth'd, the system displays a new view with all the student info. 
- [x] When going to a student profile url, if the user is not auth'd, the system redirects to login. 

## Related
- [S37](https://github.com/ProyectoIntegrador2018/BlueMarket/issues/118)

## Wireframes
(red means that it is only shown to the user logged in in their profile)
Projects tab:
<img width="871" alt="wireframe-tabProjects" src="https://user-images.githubusercontent.com/16873894/55647079-001d2180-579a-11e9-9529-dfb0b63abf70.png">

Teams tab:
<img width="889" alt="wireframe-tabTeams" src="https://user-images.githubusercontent.com/16873894/55647092-06ab9900-579a-11e9-81bc-af2f78bd5499.png">

Courses tab:
<img width="891" alt="wireframe-tabCourses" src="https://user-images.githubusercontent.com/16873894/55647104-0d3a1080-579a-11e9-9fff-c88f6b132651.png">

**Comment by katiearriagam** [comment]
![image](https://user-images.githubusercontent.com/14140121/55579845-6e98ab80-56d6-11e9-8f73-bc961a99c1f7.png)
