### ISSUE TITLE
Create student profile card

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#122]
The card presents basic student info.

## Changelog
- Created student card (studentCard.blade.php) that shows student avatar, name and skillset

## Conversation
- User basic info: name, avatar, skills. 
- It should have a link to the details user profile. (#121)

## To-do
- [x] Profile view card. (front-end)
- [x] Send user info to front-end. This includes: user basic info (name, skills, avatar, id).  (back-end)

## Acceptance criteria
- [x] When clicking on a student card, the user is redirected to the student profile url (or login view if not auth'd). 
- [x] The card displays all the user basic info. 

## Related
- [S37](https://github.com/ProyectoIntegrador2018/BlueMarket/issues/118)
- #121 
- To get user properties from database: [user-edit](https://github.com/ProyectoIntegrador2018/BlueMarket/blob/dev/resources/views/user/edit.blade.php)
- Projects view to search for projects: [projects](https://github.com/ProyectoIntegrador2018/BlueMarket/blob/dev/resources/views/projects.blade.php)
- Search projects function: [searchProjects-Function](https://github.com/ProyectoIntegrador2018/BlueMarket/blob/dev/resources/js/searchProjects.js)
