### ISSUE TITLE
System admin dropdown menu/menu

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#123]
Create the dropdown menu for teachers which is used to navigate across the application. 

## Conversation

- Must provide a way to access the views relevant to system admins (e.g. user CRU). 
- This can be either a dropdown menu or a menu for the system admin (or a combination of both). 

## To-do

- [ ] Define list of views that the system admin should be able to navigate to. 
- [ ] Define navigation to the views in the previous point. 
- [ ] Add the menu/dropdown menu and corresponding routes.
- [ ] Test navigation through the menu. 

## Acceptance criteria
- [ ] The system admin can navigate to all the views relevant to their role.
