### ISSUE TITLE
Validate navigation

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#124]
Repro all the user stories currently marked as `done` to validate that these are accessible to the user. 

## Conversation
- We should validate that all user stories marked as `done` can be completed with the currently provided naviation. 
- We should validate the findability of information for all the finished user stories. 

## To-do

- [ ] Validate each user story (preferably those that you did not work on).
- [ ] Document the user stories that you went through and write `OK` or `MISSING` depending on whether or not you found them accessible with the provided navigation elements (menus/dropdowns). 
- [ ] Open bugs for those marked as `MISSING` using the [bug template](https://github.com/ProyectoIntegrador2018/BlueMarket/blob/dev/.github/ISSUE_TEMPLATE/bug.md).
- [ ] Open bugs for those marked as `OK`, which you found hard to navigate to. Make sure to use the [bug template](https://github.com/ProyectoIntegrador2018/BlueMarket/blob/dev/.github/ISSUE_TEMPLATE/bug.md).

## Acceptance criteria
- [ ] All the user stories marked as `done` are validated.
