### ISSUE TITLE
Refactor studentProfile.blade.php

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#125]
Repro all the user stories currently marked as `done` to validate that these are accessible to the user. 

## Conversation
- csrf token is duplicated
- File name does not follow RESTful convention
- Unnecessary console logs

## To-do
- [x] Remove duplicated
- [x] Change filename
- [x] Validate ajax request - should we be using another route for this POST request?
- [x] Remove console logs
- [x] Run file through codeclimate

## Acceptance criteria
- [x] File is refatored and no duplicated are present
