### ISSUE TITLE
Move part of CourseController functionality to UserController

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#126]
Some functionality in CourseController fits better in the UserController. In particularly, this applies to student-course association scenarios.  

## Conversation
Student-course association current functionality can be broken down on two pieces:
- The student profile should display the courses that the student is currently enrolled in.
- The student should be able to associate with a course. 

Both scenarios apply to both students and courses, but I argue that they should be methods specified in the UserController instead of the CourseController because they are actions triggered by student users and both scenarios are presented in the student profile. 

## To-do
- [x] Instead of loading the user profile view from the CourseController, load the view using the UserController. 
- [x] Use method `EnrolledIn()` from the user model to gain access to the courses, instead of receiving them directly from the course controller. 
- [x] Move the method `associate(Request $request)` from the CourseController to the UserController.
- [x] Fix the necessary routes in the `web.php` file.
- [x] Fix the necessary routes in the AJAX requests. 

## Acceptance criteria
- [x] The tests relevant to [S11](https://github.com/ProyectoIntegrador2018/BlueMarket/issues/33) all pass.  

## Related
- [S11](https://github.com/ProyectoIntegrador2018/BlueMarket/issues/33)

**Comment by hecerinc** [comment]
Hay que hacerlos RESTful
