### ISSUE TITLE
Add default image in create project

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#127]
When the user does not add an image for the create project view, a default image should be used.

## Conversation
- N/A

## To-do
- [x] Check with back-end if we want to send a default image or if they store a default image. 
- [x] Remove any front-end/back-end validations for 'empty' project image.
- [x] Choose a default project image and use that on the create project view (currently using a lorempixel random image). 

## Acceptance criteria
- [x] A project can be created with a default image (no image added by user).

**Comment by katiearriagam** [comment]
@anakarenbm @hecerinc 

¿Qué les parecería mejor? ¿Que el front-end valide **antes** de enviar el form si el project image está empty (¿y si sí que mande un URL o algo a una imagen default?) o ustedes en el back-end checan si está empty y "forzan" una imagen default?

**Comment by katiearriagam** [comment]
> @anakarenbm @hecerinc
> 
> ¿Qué les parecería mejor? ¿Que el front-end valide **antes** de enviar el form si el project image está empty (¿y si sí que mande un URL o algo a una imagen default?) o ustedes en el back-end checan si está empty y "forzan" una imagen default?

Resolved this offline. No guardamos nada y lo que hacemos es que si recibimos una imagen vacía del back-end (por ejemplo, en un details view), mostramos el default image en el front-end and that's it! 😄
