### ISSUE TITLE
Update task

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#167]
## Conversation
- Update the task short description, long description, status (open/closed/ignore), deadline

## To-do
- [x] Task update view
- [x] Retrieve previous task info

## Acceptance criteria
- [x] When updating the task, the new info is saved in the DV

## Related
- #52

**Comment by katiearriagam** [comment]
# Wireframe

![image](https://user-images.githubusercontent.com/14140121/56394246-8fd7bc80-61eb-11e9-9141-969cab1e1f96.png)
