### ISSUE TITLE
project->IsProjectStakeholder($user_id) method

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#169]
## Conversation
- Gets a user id and returns a boolean that is true for users that are stakeholders of the project.

Project stakeholders include:

- team members (including team leader) of the team that owns the project
- suppliers of the project
- teachers of the client course associated with the project
- teachers of supplier courses associated with the client course

## Use case
Project stakeholders should be able to be able to read the project overview and project tasks.

## To-do 
- [ ] The method `project->IsProjectStakeholder($user_id)`
- [ ] Test that this method is working in the relevant views (project details, task update).

## Acceptance criteria
- [ ] The method is working and was tested.
