### ISSUE TITLE
project->IsProjectCollaborator($user_id) method

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#170]
# Conversation
- Gets a user id and returns a boolean that is true for users that are collaborators of the project.

## Use case
Project collaborators should be able to be able to create, read and update the project overview and the project tasks.

# To-do
- [ ] The method project->IsProjectCollaborator($user_id)
- [ ] Test that this method is working in the relevant views (project details, task update, task create).

# Acceptance criteria 
- [ ] The method is working and was tested.
