### ISSUE TITLE
project->ProjectCollaborators() method

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#171]
# Conversation
- Gets a list of users that are collaborators of a project.
- It should return the user id, the user avatar image, the user name.

## Use case
When assigning tasks to project collaborators, we need to show a list of users limited to the users that are possible project collaborators.

# To-do
- [ ] The method project->ProjectCollaborators()
- [ ] Test that this method is working in the relevant views (task update, task create).

# Acceptance criteria 
- [ ] The method is working and was tested.
