### ISSUE TITLE
Make user images squared images

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#193]
## Conversation 
Since team and project images are squared images. We should keep this consistent and make user images squared as well. 

## Todo
- [ ] Track all places where a circle user image is present 
- [ ] Make the user images squared with rounded borders 
- [ ] Suggestion: user image in user card should be shown like the project card images. 

## Acceptance criteria
- [ ] User images are squared images with round border in all places where a user image is present.
