### ISSUE TITLE
Fix milestones front-end

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#208]
## Conversation 
Milestones have some issues. 🆘 

## To-do
- [x] Remove milestones from project create.blade.php and it's respective front-end and back-end validation. @katiearriagam 
- [x] Milestones form disappears even if semantic validation fails. When validation fails, modal disappears. We should prevent this. @melytc 
- [x] Update table (milestones tab) on add and edit milestones. @melytc 
- [x] Update progress bar on add and edit milestones.  @melytc temporal hot-fix
- [x] Remove delete button from table. @katiearriagam 
- [x] Check why edit milestone button is not working. - it is working... :tada:

- [x] Add current milestone to project card. 
- [x] Current milestone in project card, when all milestones are done.
- [x] New milestone should be added in the correct order, not at the very end of the list. - Hice un fix (I think?) para esto. See: https://github.com/ProyectoIntegrador2018/BlueMarket/issues/208#issuecomment-491712784
- [ ] Can we remove the alert? If anything, I would add a modal. Pero creo que es preferible no tener nada a tener un alert. 

## Acceptance criteria
- [ ] All to-dos are finished and tested

**Comment by melytc** [comment]
Could you elaborate on these points, please?

- Add a current milestone dropdown to project (update this after adding a new milestone)
- Add is-project-done check-box (which marks all milestones as done and shows 100% progress bar)... this should empty the current-milestone dropdown (el punto de arriba).
- Check why edit milestone button is not working

Not sure when we talked about the first two, so I don't know what you are talking about.
Maybe a wire frame would be helpful, too...

**Comment by melytc** [comment]
I think these are enhancements, not issues ☺️ please add them as such.
- Add a current milestone dropdown to project (update this after adding a new milestone)
- Add is-project-done check-box (which marks all milestones as done and shows 100% progress bar)... this should empty the current-milestone dropdown (el punto de arriba).
- Add datepicker (done date) to edit milestone form (and edit milestone only) & convert date to UTC before sending to back-end. -- or was this causing a problem?

**Comment by katiearriagam** [comment]
> I think these are enhancements, not issues ☺️ please add them as such.
> 

Hm creo que sí son problemas de diseño. La segunda sería la única que consideraría un enhancement pero igual habría que hacer algo al respecto de ese escenario. 

> * Add a current milestone dropdown to project (update this after adding a new milestone)

No creo que tenga sentido que el usuario seleccione el status de cada milestone porque finalmente sólo puedes tener un current milestone por proyecto. En cuyo caso, escogerías el current milestone del proyecto. No el status de cada milestone individual. Todas las anteriores al current deberían estar en done, y las que siguen deberían estar en upcoming. Como está ahorita (status independientes de milestones), es muy fácil editar la lista y que tengan status que no tienen lógica. Por ejemplo:

- Initiate (upcoming)
- Design (current)
- Planning (done)
- ... (current)

> * Add is-project-done check-box (which marks all milestones as done and shows 100% progress bar)... this should empty the current-milestone dropdown (el punto de arriba).

Precisamente como la propuesta que dábamos @osdagoso y yo de escoger depende de escoger un current milestone por proyecto, hay que proveer una forma que permita que el progress bar se complete en 100%. Éste es el escenario en el que todos los milestones están done. Puedes hacer esto de la forma que veas conveniente. Un checkbox fue una quick go-to solution cuando encontramos el problema.

> * Add datepicker (done date) to edit milestone form (and edit milestone only) 

Si agregas un nuevo milestone, no tiene sentido que lo agregaste y ya lo terminaste. Creo que permitir esto permite malas prácticas de project management en la plataforma porque un milestone nuevo debería crearse antes de completarse, no después. Por esto, sólo deberías de poder cambiar el done date en el edit de los done milestones.

Cabe mencionar que el modelo que proponemos Oscar y yo no impide el escenario anterior. Podrías crear un milestone, ponerla antes del current milestone y ya debería estar como done (y sólo editarías el done date).

> * convert date to UTC before sending to back-end. -- or was this causing a problem?

Creo que los datetimes siempre deben guardarse en el servidor como UTC. De esta forma, tú los obtienes en front-end, formateas e independientemente del timezone, siempre muestras algo acorde al timezone del usuario, de la misma forma en que las notificaciones usan el UTC convertido según el timezone del usuario para desplegar hace cuánto tiempo se envió la notificación. Here's a scenario: si trabajas con alguien que vive en Tijuana (@osdagoso - here's to you), y marcas un milestone como done a la 1:00 de la mañana del 20 de marzo de MTY, a esta persona le debería de salir que el milestone se marcó como done a las 11:00pm del 19 de marzo.


Espero que esto aclare las dudas. I'm happy to discuss further over IM/Skype. No recibo los correos de GitHub (una disculpa) entonces esta conversación la vi por pura suerte y no quisiera bloquearte por ello. 😄

**Comment by katiearriagam** [comment]
> * [ ]  New milestone should be added in the correct order, not at the very end of the list.

Hice un fix para esto, mostly son cosas de back-end que de otra forma no te permitirían respetar el orden. No arreglé que se inserte sin tener que hacer reload, pero creo que con esto ha de ser suficiente. 

Feel free de abrir un PR de la [branch donde hice los cambios](https://github.com/ProyectoIntegrador2018/BlueMarket/tree/milestones-ordered) si quieres usar lo que propuse. No tengo mucho tiempo de mantener un PR ahorita pero espero que los cambios te ayuden y cualquier duda me puedes decir. 

cc: @rubendelapena - como tú hiciste el back-end de milestones, tú puedes saber si los cambios se ven bien o no en caso de que @melytc los quiera usar. Feel free de platicarlo entre ustedes.
