### ISSUE TITLE
Browse the projects available in the system

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#25]
# S02

Priority 1

As a user, I can see the projects available in the system to know what projects are registered in the system and learn about them.

## Conversation

- Must be filtered by category and group (class/course)

## To-do

- [] Get an object with the registered projects to the DB

- [] Filter in the front-end

- [] Integration FE and BE

## Acceptance criteria

- [] When the user load the projects view, the user is shown the projects that currently exists in the DB.

- [] When there are no projects loaded, the user is shown a message saying that there are no projects available.

- [] When the user filters by category, the user is shown only the projects that match this category

- [] When the user filters by course, the user is shown only the projects that match this course
