### ISSUE TITLE
S02 Browse the projects available in the system

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#26]
# S02

Priority 1

As a user, I can see the projects available in the system to know what projects are registered in the system and learn about them.

## Conversation

- Must be filtered by project name
- Add a tags filter (@anakarenbm @hecerinc  necesitamos tags una table en back-end, se va a cambiar **category** a **tags** (que ahora es una lista), please.
- **Tags filter must be multiselect.**

## To-do

- [x] Add dummy projects to DB (use script)

- [x] Add dummy tags and skillsets to each project in DB 

- [x] Cards should load projects from DB

- [x] Cards should be clickable and redirect to the project details view of the project they correspond to. 

- [x] Make sure search is working and filtering by **name** and **tags** (will be in another PR)

- [x] Check error validation from server side... use errors->has(input_name)
 
- [x] Add filters to project browsing view (name and tags) 

- [x] Add project details view (**see course details view for reference**).

- [x] Integration FE and BE

## Acceptance criteria

- [x] When the user load the projects view, the user is shown the projects that currently exists in the DB.

- [x] When there are no projects loaded, the user is shown a message saying that there are no projects available.

- [x] When the user filters by category, the user is shown only the projects that match this category (Will be in another PR)

- [x] When the user filters by course, the user is shown only the projects that match this course (Will be in another PR)

**Comment by katiearriagam** [comment]
@anakarenbm 

Creo que sí conviene hacer el filtering por front-end para no estar haciendo tantas llamadas a back-end. Just to be sure: el json de abajo es la información mínima que necesitaríamos para el search en el view pero queremos validar el formato. ¿Sí es algo más o menos así? 

Adicional a esto, necesitaríamos el set de `tags` para incluirlo en el input del search, please. 😊 

CC: @marcegarzab 


```js
let projects = [{
  "id": 1,
  "name": "Yeditepe University",
  "tags": [
    {
      "name": "Juice - Lime"
    },
    {
      "name": "Dish Towel"
    },
    {
      "name": "Ham - Procutinni"
    },
    {
      "name": "Soup - Campbells, Creamy"
    }
  ]
}, {
  "id": 2,
  "name": "Holar University College",
  "tags": [
  ]
}, {
  "id": 3,
  "name": "University of Science & Technology Bannu",
  "tags": [
    {
      "name": "Blueberries - Frozen"
    },
    {
      "name": "Bagel - 12 Grain Preslice"
    },
    {
      "name": "Chutney Sauce"
    }
  ]
}];
```
