### ISSUE TITLE
S05 Send invites to join my team

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#27]
# S05

Priority 1

As a team member, I can invite students to join my client team to notify them about this collaboration opportunity. 

## Conversation 
- We can do this on team creation and team edit.
- We get a list of students that we can add and throttle queries to the back-end. E.g. when the user types, every 500ms we send an AJAX request to back-end to retrieve the top 20 (?) students whose name matches what we have on our current input. 

```sql
SELECT * FROM Users
WHERE role = 3 -- student
AND name LIKE input%
AND -- user is not already a team member
LIMIT 20;
```

## To-do

- [x] Create notification center view (shared task) | 2,50 hrs
- [x] Notification component | 2,50 hrs
- [x] Load sent pending invitations and received pending invitations (shared task) | 1,00 hrs
- [x] Update team view - include user dropdown | 2,00 hrs
- [x] Add hasAccepted field to TeamUser table | 0,50 hrs
- [x] Create and read backend functions for TeamUser (consider creating mini-lib for this) | 2,00 hrs
- [x] Create model for TeamUser | 1,00 hrs
- [x] Generate Eloquent functions for User (sentInvites, receivedInvites) | 1,50 hrs
- [x] Create enum for invite status | 0,50 hrs
- [x] PR | 3,00 hrs
- [x] Integration | 2,00 hrs
- [x] Pruebas | 1,50 hrs
- [x] User manual | 0,50 hrs

## Acceptance criteria

- [x] When the student sends the request, the team leader must be able to see it.
- [x] The request notification must be shown on the DB

**Comment by katiearriagam** [comment]
## Wireframes
![image](https://user-images.githubusercontent.com/14140121/56854297-b12a5e00-68f9-11e9-90fd-5a87411b4d34.png)
