### ISSUE TITLE
S08 Accept a team leader's invite to join their team

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#28]
# S08

Priority 2

As a student, I can accept a team leader's invite to **join their team** to become associated with it. 

## Conversation

- Can accept or ignore request.

- TBD: Limited to the team's capacity.

## To-do

- [x] Frontend: view notifications / notification component (accept/reject) | 1,50
- [x] Change invite status | 1,00
- [x] Delete rejected invite | 1,00
- [x] PR | 2,00
- [x] Integration | 2,50
- [x] Pruebas | 3,50
- [x] User manual | 0,50

## Acceptance criteria

- [x] When the team leader approves a request, the notification must no longer show on the notification view/DB and the new association is made on the DB.

- [x] When the team leader ignores a request, the notification must no longer show on the notification view/DB.

**Comment by katiearriagam** [comment]
## Wireframe

![image](https://user-images.githubusercontent.com/14140121/56834735-d8205b80-6837-11e9-9c0d-50473b57bc63.png)
