### ISSUE TITLE
S04 Update my profile

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#29]
# S04

Priority 1

As a student, I can update my profile to show my skills to update my information on the system.

## Conversation 

- Editable fields: photo, name, skills

## To-do

- [x] Edit view

- [x] Update process on back-end to modify DB

- [x] For skills, ensure we delete those that the user removes and add the new ones. 

- [x] Verify that the user for which we are modifying the info is the one signed in.

- [x] Integration FE and BE

## Acceptance criteria

- [x] When the user edits their data, these must be modified in the DB. 

- [x] Input validation is performed every time a user tries to update their info.

**Comment by katiearriagam** [comment]
# Wireframe

![image](https://user-images.githubusercontent.com/14140121/54329487-771a2c80-45d7-11e9-8328-989c338c8f0a.png)
