### ISSUE TITLE
S10 Define the pool of courses my students can work with

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#30]
# S10

Priority 1

As a teacher, I can define the pool of courses my students can work with to enable them to create associations between courses

## Conversation

- The pool should show as a list of the currently available courses in the DB

- Courses must include the professor's name, course name and group id (e.g. 'Prof. Xavier, Computer Graphics, 112')

- TBD: only client courses identify supplier courses

## To-do

- [x] Create the component that shows this pool - consider fuzzy search

- [x] Load the courses from the DB 

- [x] Create the association on the DB 

## Acceptance criteria

- [x] When a teacher defines the pool of courses, a student from a supplier team which has been added can see the teams from this course. 

- [x] When a teacher defines the pool of courses, the DB should show the available associations.
