### ISSUE TITLE
S14 See bluemarket events/milestones

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#31]
# S14

Priority 3

As a student, I can see the system-specified milestones/events to learn more about them.

## Conversation 

- There are 3 mandatory deadlines/milestones for all projects: Mid checkpoint, Final delivery (clients deliver final product), Acceptance letter delivery

- TBD: separate them by upcoming/overdue? Only upcoming?

## To-do 

- [ ] Query the milestones/events 

- [ ] In the front-end, separate them by upcoming/overdue

- [ ] Create the view of the milestones

- [ ] FE and BE integration

## Acceptance criteria

- [ ] When the student accesses the bluemarket milestones section, it must load the milestones from the DB.

- [ ] If no upcoming milestones, it must show a message saying so.
