### ISSUE TITLE
S13 Specify system milestones/events

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#32]
# S13

Priority 3

As a system admin, I can specify system milestones/events to share them with students. 

## Conversation

- There are 3 mandatory deadlines/milestones for all projects: Mid checkpoint, Final delivery (clients deliver final product), Acceptance letter delivery 

## To-do

- [ ] Generate the milestones/events view for SA.

- [ ] Generate the milestones/events upload components for SA.

- [ ] Set milestones/event in DB

- [ ] FE and BE integration.

## Acceptance criteria

- [ ] When the SA sets a new deadline, it should appear on the DB.
