### ISSUE TITLE
S11 Associate myself with a course 

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#33]
# S11

Priority 1

As a student, I can associate myself with a course given a course key to access the course view

## Conversation
- The course key must be generated by the teacher when the course is registered
- Course view includes: Course name, professor, type of course

## To-do
- [x] Create view to add student to course (front-end)

- [x] Input validation

- [ ] Validate the course key (back-end)

- [x] Show preview of which course is getting associated with the course key (front-end)

- [ ] Send preview of course key (back-end)

- [ ] Store student-course association on DB when accepted by student (back-end) 

- [x] Show completion/error message (front-end)

- [ ] Show course associations in student profile (front-end and back-end)

### Preconditions: 
- Student is logged in

### Flow
1. **Student** enters a class code which is valid in the DB.
2. **System** shows details of the course: course name, professor, class schedule.
3. **System** asks student to confirm course association given the details.
3. **Student** confirms association.
4. **System** saves association in the DB and shows it in the student profile.

### Postconditions: 
- Student is associated with a course and the association is shown in the student's profile

## Acceptance criteria
- [ ] If the course key is valid, the student must be associated with it and the association must be reflected in the DB. 

- [ ] If the course key is invalid, an error message is shown and the association is not made

**Comment by katiearriagam** [comment]
### Wireframes
![image](https://user-images.githubusercontent.com/14140121/53455782-4d66e000-39f1-11e9-8b93-5bde682cd497.png)
