### ISSUE TITLE
See details about possible projects

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#34]
Priority 1

As a supplier, I can see the details about the matched possible projects to gain information on the project.

## Conversation

- The details include the project's info (when added), the team members that own it (with a link to their profiles).

- If you need anything backend side let me know (En el show de Projects en el backend les enviamos `$project` y ese modelo debe ya tener toda la info que necesitan) - @anakarenbm 

## To-do
- [x] Create Project Details view
- [x] Embed youtube video 

## Acceptance criteria
- [x] When a user clicks on a project card, a new view should load showing all project info. 
- [x] When modifying the URL manually to see another project, the project details view only loads if the user is signed in.

**Comment by katiearriagam** [comment]
@anakarenbm - tenía entendido por ahí que nosotros mandabamos el url de youtube y back-end lo limpiaba y lo dejaba listo con el formato listo para embed. Idk if this is done pero si no, eso sí hace falta. 😄

**Comment by anakarenbm** [comment]
True! not done yet 🙈
