### ISSUE TITLE
S06 Send invite to join my project

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#35]
# S06

Priority 1

As a team leader, I can send invites to students enrolled in supplier courses associated with my client course to invite them to collaborate on my project. 

## Conversation  

- This must be restricted by whether the client team is already associated with a supplier team from the supplier course.

- The client teacher will define which supplier courses can be associated with their course. Only supplier teams from these courses may request this associaton. 

## To-do
- [x] Update project view - include user dropdown | 1,50
- [x] Notification component | 2,50
- [x] Define table: ProjectSupplier | 1,50
- [x] Generate ProjectSupplier entry when invite is sent | 0,00
- [x] Create and read backend functions for ProjectSupplier | 2,00
- [x] PR | 5,00
- [x] Integration | 3,50
- [x] Pruebas | 1,50
- [x] User manual | 0,50

## Acceptance criteria

- [ ] When the request is sent, the notification must show on the DB.

**Comment by katiearriagam** [comment]
## Wireframe

![image](https://user-images.githubusercontent.com/14140121/56854240-fac67900-68f8-11e9-8e8b-74eb2b6105c7.png)
