### ISSUE TITLE
S03 Register a course on the platform

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#36]
# S03

Priority 1

As a teacher, I can register a course on the platform to enable my students to associate themselves to it.

## Conversation

- Must generate a course key

## To-do

- [x] View to register a course on the platform

- [x] Course creation success view

- [x] Generate a code key for the course

- [x] Form input validation

- [x] Integration FE and BE

## Acceptance criteria

- [x] When a teacher creates a course, a new course must show on the DB.

- [x] When a teacher create a course, a unique key must be generated for it.

**Comment by melytc** [comment]
### Wireframe
![img_0443](https://user-images.githubusercontent.com/8518253/53382840-277f0400-393b-11e9-9bcf-ba0b5e6377b3.JPG)

**Comment by katiearriagam** [comment]
### Notes

1. ¿Un maestro puede dar de alta cursos donde otro maestro sea el encargado?
		- Sólo dan de alta sus cursos
		- Super admin puede agregar cursos (esto es otra user story)
2. ¿Puede haber múltiples maestras encargadas de un curso?
		- Sí se da la opción de agregar un maestro al curso, debe de tener acceso a todo lo del curso.
3. Campos que se dan de alta en el curso:
		- Course name
		- Professor (possibly pre-loaded)
		- Schedule
		- Max. number of students per team
		- Affiliated courses
		- Type of course: client/supplier

**Comment by katiearriagam** [comment]
> ### Wireframe
> ![untitled_artwork 2](https://user-images.githubusercontent.com/8518253/53384417-70858700-3940-11e9-95cc-6df56ffc4083.jpg)

@melytc: wondering si el course schedule puede ser:
1. un grupo de checkboxes (para agregar los días)  (Monday-Saturday)
2. un dropdown de horas con opciones de cada 30 minutos entre 7:00-21:00. ¿Qué opinas? 
3. como stretch, haría un dropdown del semestre (Fall 2018, Spring 2019), porque podemos tener el record de un curso por mucho tiempo. 

Al pasarle a @osdagoso los días puedes hacer una relación para ir appending los días que seleccionó (#1) y la hora (#2)... sólo necesitamos el start time porque esto sólo es para ayudar al estudiante y maestro a identificar su grupo. 

De este modo, un **course schedule** se vería: MoThu 14:30, Spring 2019.

Queda a su consideración completamente. Just putting it out there. :)

**Comment by melytc** [comment]
Por lo pronto, lo dejamos un poco más sencillo:
<img width="1488" alt="screen shot 2019-02-28 at 9 22 25 pm" src="https://user-images.githubusercontent.com/8518253/53614271-01599e00-3b9f-11e9-8468-4d7b6df07e02.png">

@katiearriagam 
1. Para los días es el mismo ui fluid search dropdown con los 5 días de la semana (¿hay algún caso que una clase se dé en fin de semana?)
2. La hora es un time input de 24 horas :)
3. Y quedamos que el semestre lo dejaríamos por ahora como un texto, por si en el futuro cambian en el Tec (#Tec21).

😄
