### ISSUE TITLE
S09 Define a maximum number of members per team for my courses 

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#37]
# S09

Priority 3

As a teacher, I can define a maximum number of members per team for my courses to limit the associations that can be made.

## Conversation

- This should constrain the associations other students/suppliers can make to this team.

- Related: [S08](https://github.com/ProyectoIntegrador2018/BlueMarket/issues/28) and [S32](https://github.com/ProyectoIntegrador2018/BlueMarket/issues/48) Need to add constraint to approve or send requests if the team is full. Consider simply not showing the team to supplier teams.

- Professor needs control over this. 

- TBD: only show the teams that have available capacity when a student looks for them. If no teams available, show this message.

## To-do

- [ ] Add this to the register section of a course

- [ ] Specify the capacity on the DB

- [ ] Use this to prevent association approvals from suppliers and other students

- [ ] Integration FE and BE

## Acceptance criteria 

- [ ] When a teacher adds the capacity of a group, the DB needs to show this capacity. 

- [ ] TBD: when a teacher defines the capacity, a student from this course can only see the teams that have not yet reached full capacity. 

- [ ] If there are no teams with available capacity, the student view of teams must show a message with this information.
