### ISSUE TITLE
S21 Update a task's status

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#39]
# S21

Priority 2

As a team member, I can update the status of an associated project's tasks to keep task lifecycle data up to date.

## Conversation  

- Possible status: todo, in progress, closed
- It can be modified after being closed
- All project collaborators can 

## To-do

- [x] Add task status section to create/update task view

- [x] Query to update a task's status

- [x] Integration FE and BE

## Acceptance criteria

- [x] When a team member changes a task's status, this must be modified in the DB and the view.

**Comment by katiearriagam** [comment]
Related PRs:
- #185
- #226
- #225 
- #229
