### ISSUE TITLE
S07 Accept a team leader's invite to collaborate on a project as a supplier

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#40]
# S07

Priority 2

As a supplier, I can accept a team leader's invite **to collaborate on their project** to become associated to it. 

## Conversation
- Can accept or ignore request.

## To-do

- [x] Frontend: view notifications / notification component (accept/reject) | 2,00
- [x] Change invite status | 1,00
- [x] Delete rejected invite | 1,00
- [x] PR | 3,50
- [x] Integration | 3,00
- [x] Pruebas | 3,50
- [x] User manual | 0,50

## Acceptance criteria

- [ ] When the team leader approves a request, the notification must no longer show on the notification view/DB and the new association is made on the DB.

- [ ] When the team leader ignores a request, the notification must no longer show on the notification view/DB.

- [ ] When the team is already associated with a supplier from the same course, the request cannot be approved and the team leader must be notified.

**Comment by katiearriagam** [comment]
## Wireframe
![image](https://user-images.githubusercontent.com/14140121/56834724-cfc82080-6837-11e9-839b-302c916404c2.png)
