### ISSUE TITLE
S19 See project tasks

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#41]
# S19

Priority 1

As a project stakeholder (team leader, team member, supplier, professor of client/supplier course), I can see the project tasks.

## To-do
- [x] List of tasks view (group them by pending, overdue and done)
- [x] Task details view (possibly part of the project details view, but only visible to project collaborators)
- [x] Retrieve all project tasks 
- [x] Retrieve each task details (for task details view)
- [x] Integration FE and BE

## Acceptance criteria
- [x] When a project stakeholder goes to the project task list, all tasks are presented and grouped.
- [x] When a project stakeholder goes to each task details, the task view is presented.

**Comment by katiearriagam** [comment]
# Wireframes

# Task list (inside project details)

![image](https://user-images.githubusercontent.com/14140121/56381442-b71d9200-61c9-11e9-93fd-7ac7cde14d2e.png)


Notes: 
- Overview is based on @melytc's suggestions in #163. Aquí no van los project milestones son de otro issue. 
- Tabs view is only shown for project stakeholders (team members, supplier, teachers (of the course associated with the project and the supplier courses)). 
- If the user is not a project stakeholder, the overview is shown without the tabs (as seen on #163).
- @melytc, @marcegarzab -> feedback is very welcome :) 


# Task details view
![image](https://user-images.githubusercontent.com/14140121/56381646-5773b680-61ca-11e9-8f56-6b5808bbfa6f.png)

**Comment by marcegarzab** [comment]
Me parece muy bien el layout de la página, solamente tengo duda de que hace el botón de "open" en el task detail view?

**Comment by katiearriagam** [comment]
Debí haber sido más específica jajajaj. en realidad es sólo un pill que indica el status actual del task. :)

**Comment by katiearriagam** [comment]
Related PRs:
- #185
- #226
- #225 
- #229
