### ISSUE TITLE
S18 Set task deadlines for my projects

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#42]
# S18

Priority 1

As a team leader, I can set task deadlines for projects that I am associated with to add a time constraint to project tasks.

## Conversation  

- A task can have a maximum of one task deadline attached to it 
- TBD: which students can create the deadline? 
- All tasks require deadlines

## To-do

- [x] Add task deadline section to create/update task view
- [x] Query to set/update deadline field on task entry
- [x] Integration FE and BE

## Acceptance criteria
- [x] When a team leader  sets a task deadline, this must be modified in the DB.

**Comment by katiearriagam** [comment]
Related PRs:
- #185
- #226
- #225 
- #229
