### ISSUE TITLE
S33 Browse projects from another course (supplier)

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#43]
# S33

Priority 1

As a supplier, I can browse projects from another course to request association to them.

## Conversation  

- This must be restricted by whether the client team is already associated with a supplier team from the supplier course.

- The client teacher will define which supplier courses can be associated with their course. Supplier teams will only see the projects for which they are part of the possible collaborators pool.

## To-do

- [ ] View of projects I can associate with (cards?)

- [ ] Query of the courses 

- [ ] Team leader notification view

- [ ] Integration FE and BE

## Acceptance criteria

- [ ] When the user loads the view of possible projects, it must load all the projects that the user can be associated with.

- [ ] If no projects match, show a message saying so.
