### ISSUE TITLE
S31 Delete a course from the platform

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#44]
# S31

Priority 3

As a teacher, I can delete a course from the platform to prevent students from associating to it on the system.

## Conversation

- Must delete all student and project associations to it. 

- Define if this is a client or supplier course.

## To-do

- [ ] View of all my courses to see delete

- [ ] Delete process on back-end

- [ ] Integration FE and BE

## Acceptance criteria

- [ ] when a teacher deletes a course, it must not longer exist on the DB.
