### ISSUE TITLE
S28 Update a project

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#45]
# S28

Priority 1

As a student, I can update a project and its information to keep the information up to date.

## Conversation

- Required fields CANNOT be erased and left blank

- TBD: should users be able to modify completed projects' information?

## To-do

- [ ] Create update project view

- [ ] Implement form validation

- [ ] Query to retrieve project information

- [ ] Query to update project information

- [ ] Integration FE and BE

## Acceptance criteria

- [ ] When a student updates a project, its information should be updated in the DB.
