### ISSUE TITLE
S29 CRU users and set their roles

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#46]
# S29

Priority 1
As a system admin, I can CRU users and set their role to give them access to the system.

## Conversation

- A system admin can CRU information of:
  - student
  - professor
  - system admin

## To-do

- [x] Wireframes (1.0h)
- [x] Generate view of list of users (1.5h)
- [ ] Add a search bar to look up a certain user by name and email (1.5h)
- [x] Generate view for user information (1.0h)
- [x] Generate view to create a user (1.0h)
- [x] Generate view to update a user (1.0h)
- [x] Input validation for create and update procedures (2.0h)
- [x] Success/error views for CRU (0.5h)
- [x] Fetch of users' data (1.0h)
- [x] Fetch of each user for details (1.0h)
- [x] Create procedure (1.0h)
- [x] Update procedure (1.0h)
- [x] Integrate admin layout from template (1.0h)
- [x] Integration FE and BE (2.0h)

## Acceptance criteria

- [x] When a user is created, it should be reflected in the database as a new entry.
- [ ] When a user is queried, it should be reflected in the system admin's view.
- [x] When a user is updated, it should be reflected in the database as a modified entry.

**Comment by melytc** [comment]
# Wireframes
![image](https://user-images.githubusercontent.com/8518253/54080066-fa711080-42ad-11e9-8128-860851ac0c0a.png)

**Comment by melytc** [comment]
# CRU Tests

## Index view
- [x] New button redirects to `Create User` view
- [ ] Search bar can filter (Checarlo con Rubén)
  - [ ] Name
  - [ ] Email
  - [ ] Role
- [x] Shows all users in database correctly
- [x] When selecting a user (in any of its fields), redirects to correct `View User` view
- [x] When selecting Edit button of a user, redirects to correct `Edit User` view
- [ ] Footer pagination dynamism, based on number of users sent from backend
- [x] Test view responsiveness


## Create User view
- [x] Create a student
- [x] Create a teacher
- [x] Create an administrator
- [ ] Validate name input with error messages
- [ ] Validate email input with error messages
- [ ] Validate role input with error messages
- [x] Back button redirects to `Index` view
- [x] Test view responsiveness
**Notes:**
- Input validation and errors not showing up


## View User view
- [x] User data is shown correctly
- [x] Back button redirects to `Index` view
- [x] Edit button redirects to `Edit User` view
- [x] Test view responsiveness


## Edit User view
- [x] User data is shown correctly
  - [ ] Role is not correctly selected with user data
- [x] Update user
- [ ] Validate name input with error messages
- [ ] Validate email input with error messages
- [ ] Validate role input with error messages
- [x] Back button redirects to `Index` view
- [x] Test view responsiveness
**Notes:**
- Input validation and errors not showing up
