### ISSUE TITLE
S24 Upload files to project

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#47]
# S24

Priority 1

As a team member or supplier I can upload files to a project that I am associated with to share documents with those involved in the project.

## Conversation

- Files should only be available for those involved in the project

- TBD: Are there any restrictions to file extensions?

## To-do

- [ ] Add upload files view/modal

- [ ] Query to store files as BLOBs

- [ ] Back-end encoding work for storing files

- [ ] Integration FE and BE

## Acceptance criteria

- [ ] When a team member or supplier uploads a file to a project, its entry should be added in the DB.
