### ISSUE TITLE
S32 Browse teams from my courses

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#48]
# S32

Priority 1

As a student, I can browse teams from the courses that I am associated with to request association to them. 

## Conversation 

- This must be restricted by the capacity of each team (as defined by the teacher). Teams with full capacity must not show.

## To-do

- [ ] Generate browsing view

- [ ] Generate team card?

- [ ] Query all available teams

- [ ] Query all current team members of a team

## Acceptance criteria

- [ ] When the student browses a team, the system must show only the teams where students' courses match

- [ ] If no teams match, show a message saying so
