### ISSUE TITLE
S20 Assign tasks to my team members

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#49]
# S20

Priority 1

As a team member, I can assign tasks to my team members for the projects that I am associated with to establish links between team members and project tasks.

## Conversation  

- There is no defined limit for how many tasks can be attached to a team member
- Only one assignee per tasks
- All project collaborators can assign tasks

## To-do

- [x] Add task assignee section to create/update task view
- [x] Query to fetch team members
- [x] Query to fetch tasks
- [x] Query to create task-team member association
- [x] The task assignation must be reflected on the view
- [x] Integration FE and BE

## Acceptance criteria

- [x] When a team member assigns a task to someone, the association must be shown in the DB.
- [x] When a team member assigns a task to someone, the association must be shown in the view.

**Comment by katiearriagam** [comment]
Related PRs:
- #185
- #226
- #225 
- #229
