### ISSUE TITLE
S17 See files uploaded by my students

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#50]
# S17

Priority 2 

As a teacher, I can see the files uploaded by my students to their projects associated with my course, to view their progress.

## Conversation

- Projects are associated with a course (TBD: courses), professor from this courses may access the project's files.

## To-do

- [ ] Generate DB query to retrieve all projects associated with the courses that the professor is teaching. 

- [ ] Sort query by updated files.

- [ ] For each project, view with all the corresponding files.

## Acceptance criteria

- [ ] When a teacher accesses the files view, a view of all files associated with their courses is shown in submission order.
