### ISSUE TITLE
S22 Set a project's milestone

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#51]
# S22
Priority 1
As a team leader, I can set a project’s milestone to make the project's state public.

## Conversation  
- Related to S12
- An initial milestone must be set when creating a project
- Fixed milestones:
1. Ideation
2. Design
3. Planning
4. Execution
5. Tests
- Custom milestones can be added between any fixed milestones. 

## To-do
- [x] Frontend: Wireframes and validation (1.5h)
- [x] Backend: Add fixed milestiones upon project creation. (1.5h)
- [x] Frontend: Add progress bar and milestones section in `Project Details` view. (2.5h)
- [x] Frontend: Create `Add milestone` view. (1.5h)
- [x] Backend: CRUD milestone (4h)
- [x] Integration FE and BE (1.5h)
- [x] PR (4h)
- [x] Testing (3h)

## Acceptance criteria
- [x] When a team leader creates a projects, fixed milestones appear on `Project Details` view.
- [x] When a team leader adds a milestone, it must be added to the project's entry in the DB and it is reflected in the milestones section.

**Comment by melytc** [comment]
## Wireframe
![IMG_5502](https://user-images.githubusercontent.com/8518253/56307294-60e11e00-60f9-11e9-8774-7e44f3e947d4.JPG)

## Proposal
(For general view, missing milestone crud for team leader)
Add a Progress section in Project's Details page, and display:
- Progress bar
- Current milestone
- See milestones button

When *See milestones* button is clicked, display hidden section below with each milestone and its done date.

A milestone can be displayed as:
- **Done**: faded color
- **Current**: saturated color
- **Coming up**: gray color

## To be defined (by client)
- Is it enough to store/display the done date? 
- Do we need to keep track of estimated dates?

**Comment by melytc** [comment]
## Current view
### Default view
![Screenshot_2019-04-21 Bluemarket - Solarbreeze(2)](https://user-images.githubusercontent.com/8518253/56476111-9e221480-6447-11e9-9b61-58525b58820a.png)

### When clicked on See milestone button
![Screenshot_2019-04-21 Bluemarket - Solarbreeze(1)](https://user-images.githubusercontent.com/8518253/56476017-8fd2f900-6445-11e9-8e6c-732ebe610c83.png)

- *Edit milestone map* button will be available only for team leader. 
- This will redirect user to milestone map index (milestones/index) with a table of all project's milestones. There a user can edit a milestone: change name, previous milestone, estimated date and status.

![IMG_8678](https://user-images.githubusercontent.com/8518253/56476117-c3168780-6447-11e9-849e-d1f7666537e7.JPG)

## Backend consideration
- We need a milestone entity, with name, status (done, current, coming-up), estimated_date, done_date (recorded when user marks the milestone as done), and previous_milestone (id referencing another milestone) attributes.
- We need a 1:N relationship between project and milestone (a project can have multiple milestones).
- Upon creation, a project **should** have the 5 basic milestones:
1. Ideation
2. Design
3. Planning
4. Execution
5. Test

I think this might be the easiest way to tackle the milestones' feature. Feedback is welcomed! 🐙
