### ISSUE TITLE
S25 Create task for project

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#52]
# S25

Priority 1

As a project collaborator (team leader, team member, supplier), I can create tasks for an associated project to detail the project workflow.

## Conversation
- There isn't a maximum number of tasks that can be created for a project
- TBD: Must tasks have an initial deadline set before creation? Yes, let's assume this
- `tasks` table has the following fields: `title`, `description`, `due_date`, `task_status` -> enum `[
        'pending' => 1,
        'overdue' => 2,
        'done' => 3,
	]` and a `project_id`
## To-do
- [x] Create task view
- [x] Input validation
- [x] Save task on DB associated to the project
- [x] Integration FE and BE

## Acceptance criteria
- [x] When a team member creates a new task, its entry should be added in the DB.
- [x] The task must be associated to a project

**Comment by katiearriagam** [comment]
# Wireframe
![image](https://user-images.githubusercontent.com/14140121/56394286-aaaa3100-61eb-11e9-97cb-d3425c2b8a94.png)

**Comment by katiearriagam** [comment]
Update: 
- Status is not relevant here. We assume `open` for all new tasks.
- Assignees are for layout purposes only. These are not included in this issue, but rather on #49

**Comment by katiearriagam** [comment]
Related PRs:
- #185
- #226
