### ISSUE TITLE
S26 See tasks associated with one of my projects

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#54]
# S26

Priority 1

As a team member, I can see tasks associated with one of my projects to be aware of the project's workflow.

## Conversation

- Tasks must be categorized in "to-do", "in progress" and "complete" tasks.

## To-do

- [x] Add tasks section to project view

- [x] Query to retrieve project's tasks

- [x] Integration FE and BE

## Acceptance criteria

- [x] When a team member visits a project's page, its tasks should be visible in a list.

**Comment by katiearriagam** [comment]
Related PRs:
- #185
- #226
- #225 
- #229
