### ISSUE TITLE
S30 View project milestones

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#55]
# S30

Priority 1

As a student, I can see the project milestones for any project to know the status of the project.

## Conversation

- The team leader is the only user who can set the project milestones.
- Every user must be able to see these (external site)
- Milestones fijas:
1. Ideación 
2. Diseño
3. Planeación
4. Ejecución
5. Pruebas

- Intercalar milestones personalizadas entre las milestones fijas. 

- Pasar de la etapa de diseño -> desarrollo -> deployment

## To-do
- [x] Add a milestone progress section in the project details
- [x] Add a milestone details in project details

## Acceptance criteria

- [x] The system should show the current project milestone the team is at, and the next steps.

**Comment by melytc** [comment]
Creo que este user story ya lo cubrimos con el S22 (#51) / S23 (#53) 👀 👀
