### ISSUE TITLE
S12 As a student, I can register a new project on the platform

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#6]
### Related

- [x] Frontend #7 
- [x] Backend 
    - [x] #8  
    - [x] #9 

### To-do
- [x] Form input validation 
- [x] KATIE: validar fields del proyecto
- [x] User will have to upload a photo (resize it for the different display sections) #13 
    - [x] FRONTEND: specify sizes for frontend views (for resizing)
- [x] Fuzzy search the skills (fixed set con alternativa de subir tu opcional) 

@marcegarzab @anakarenbm: 
Hay un nuevo task a considerar con ésta user story. Lo íbamos a separar pero nos dimos cuenta de que en realidad debería ser un nuevo task. 
- [x] I can register a project in one of **my associated courses** with its information.

#### Pending
- [x] Check image size
- [x] Check image type (accept only jpg and png)
- [x] Show new image on preview after it is uploaded **and** it has passed size and type validation.
- [x] For the YouTube project video, use [regex](https://semantic-ui.com/behaviors/form.html#content-type) validation to check for a **youtube url**. Useful resource: [Regex for youtube URL](https://stackoverflow.com/questions/19377262/regex-for-youtube-url)
- [x] Change project video error message to something like: "Please enter a valid youtube url". 
- [x] Test input validation
- [x] Fill all remaining dropdowns and multi-selects the same way you loaded the associated courses.
- [x] Fix codeclimate issues after pushing to your branch (some might not apply. Please check with @hecerinc). 

##### Fuzzy search resources

1. Semantic UI has a [Multiple Search Selection](https://semantic-ui.com/modules/dropdown.html). Consider using this one. 
2. Another option is  [selectize.js](https://selectize.github.io/selectize.js/)

### Conversation

- Pitch video: link de youtube (that we should embed always on the platform)
- Los fields están en el glosario en los reqs - hay que considerar todos los del view de detalles para el registro de un nuevo proyecto.

Fields para el public-facing view (non-authenticated users):

- project name
- project photo
- required skill set
- project description (short)
- public milestones
- category

Fields para el full detail view del proyecto (authenticated users):

- team name
- team members (siempre no va ir aqui)
- project name
- video pitch
- project photo
- required skill set
- project description (long)
- project description (short)
- public milestones
- category

<img width="799" alt="wireframeregisterproject" src="https://user-images.githubusercontent.com/16873894/53198561-4b141880-35e2-11e9-8020-806f575f1804.png">
