### ISSUE TITLE
Frontend future fixes for next sprint

### ISSUE THREAD

**Issue by melytc** [ProyectoIntegrador2018/BlueMarket#75]
## Conversation 
Pending miscellaneous requested by client from previous sprints.

## To-do's
- [x] Input validation through semantic ui
- [x] Description paragraph visible in course registration view
- [x] Teacher create course, show error messages by field (which is wrong) | 1,50
- [x] Teacher create course, description paragraph visible instead than on-hover | 1,50
- [x] Teacher create course, migrate input validation through semantic ui instead of js | 2,50
- [x] Teacher create course enhancements: PR | 1,50

## Acceptance criteria
- [x] All to-dos in the list above are done

**Comment by katiearriagam** [comment]
@melytc 

no estoy segura si esto ya está hecho le puse los tags y lo agregué al project pero tú sabrías mejor que yo si pertenece al current sprint o qué
