### ISSUE TITLE
S32 View course details (teacher)

### ISSUE THREAD

**Issue by melytc** [ProyectoIntegrador2018/BlueMarket#82]
# S32
Priority 1
As a teacher, I can view my course details to validate my information, and retrieve my course key.
(Estimated time: 6.5 hours)

## Conversation  
- This is the redirected view when creating a course.
- (Ask client which details are supposed to be shown when displaying list of courses for a teacher)

## To-do
- [x] View of list of teacher's courses. (1.0 hours)
- [x] Fetch of teacher's courses. (1.0 hours)
- [x] Redirection from list to details view. (0.5 hours)
- [x] View course details with real data. (1.0 hours)
- [x] Correct routing from create course view to its course details. (0.5 hours)
- [x] Integration FE and BE. (1.5 hours)
- [x] PR and peer reviewed (1.0 hours)

## Acceptance criteria

- [x] When a teacher creates a course, the user is redirected to its course details.
- [x] Information is consistent with the information given when created (including generated course key).
