### ISSUE TITLE
S33 Create team

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#91]
# S33

Priority 1

As a student, I can create a team on the platform to group students on the platform. 

## Conversation
- Image must be squared
- Creating a team includes: team name, team photo.
- The student who creates the team must be designated as team leader.

## To-do
- [x] Wireframe - actualizar en user story de Github + documento (0.8 h)
- [x]  Form to create team (2 h) 
- [x]  Create procedure (2 h)
- [x]  Create migration for Team table (1 h) 
- [x] Create model for Team (1 h)
- [x] Success view (team details) (2.5 h)
- [x] Error handling (1 h)
- [x] Input validation using semantic UI (1 h) 
- [ ] Diseñar pruebas (1.5 h)
- [ ] Correr pruebas (actualizar documento de pruebas) (1 h)
- [ ] Integracion FE y BE (1.5 h)
- [ ] PR (1 h)

## Acceptance criteria
- [ ] When completing team creation successfully, the system should show the team profile with the team members populated by the team leader.

**Comment by katiearriagam** [comment]
# Wireframe
![image](https://user-images.githubusercontent.com/14140121/54077170-8d905300-427a-11e9-83b2-ca2e576d2f2d.png)

**Comment by hecerinc** [comment]
Esto de las fotos de los teams es parte de lo que validaste con Lorena, @katiearriagam ?

**Comment by katiearriagam** [comment]
> Esto de las fotos de los teams es parte de lo que validaste con Lorena, @katiearriagam ?

¿El avatar? Sip.
